//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcodev.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class duyurular
    {
        [Required(ErrorMessage = "bu alan boþ geçilemez")]
        public int id { get; set; }
        [Required(ErrorMessage = "bu alan boþ geçilemez")]
        public string baslik { get; set; }
        [Required(ErrorMessage = "bu alan boþ geçilemez")]
        public string icerik { get; set; }
       
        public string resim { get; set; }
    
    }
}
