//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcodev.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class kullanici
    {
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public int kullanici_id { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string kullanici_adi { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string kullanici_soyadi { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string kullanici_girisadi { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string kullanici_girissifre { get; set; }
      
    }
}
