//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcodev.Models.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mvcveriEntities5 : DbContext
    {
        public mvcveriEntities5()
            : base("name=mvcveriEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adminsayfalar> adminsayfalar { get; set; }
        public virtual DbSet<duyurular> duyurular { get; set; }
        public virtual DbSet<hakkimizda> hakkimizda { get; set; }
        public virtual DbSet<iletisim> iletisim { get; set; }
        public virtual DbSet<kullanici> kullanici { get; set; }
        public virtual DbSet<mekan> mekan { get; set; }
        public virtual DbSet<resimler> resimler { get; set; }
        public virtual DbSet<rezervasyon> rezervasyon { get; set; }
        public virtual DbSet<sanatcilar> sanatcilar { get; set; }
        public virtual DbSet<sayfa> sayfa { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<uyebilgi> uyebilgi { get; set; }
        public virtual DbSet<uyesayfa> uyesayfa { get; set; }
        public virtual DbSet<yemekler> yemekler { get; set; }
    }
}
