//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcodev.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class rezervasyon
    {
       
        public int id { get; set; }
     
        public string tarih { get; set; }
     
        public string davetli { get; set; }
        
        public string kullanici_detay { get; set; }
      
        public Nullable<int> mekan_id { get; set; }
       
        public Nullable<int> menu_id { get; set; }
    
        public Nullable<int> sanatci_id { get; set; }
    
        public virtual mekan mekan { get; set; }
    
        public virtual sanatcilar sanatcilar { get; set; }
     
        public virtual yemekler yemekler { get; set; }
       
    
    }
}
