//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcodev.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class sanatcilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sanatcilar()
        {
            this.rezervasyon = new HashSet<rezervasyon>();
        }
    
        public int sanatci_id { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string sanatci_tc { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string sanatci_ad { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string sanatci_muzik { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string sanatci_telefon { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string sanatci_mail { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public Nullable<int> sanatci_yas { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public Nullable<int> sanatci_ücret { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string sanatci_video { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string sanatci_cinsiyet { get; set; }
       
        public string sanatci_fotograf { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rezervasyon> rezervasyon { get; set; }
    }
}
