//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcodev.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class uyebilgi
    {
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public int üye_id { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string üye_adi { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string üye_soyadi { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string mail { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string tarih { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string cinsiyet { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string kullanici_adi { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string sifre { get; set; }
      
    }
}
