//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcodev.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyesayfa
    {
        public int sayfa_id { get; set; }
        public string sayfa_adi { get; set; }
        public string sayfa_link { get; set; }
    }
}
