//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcodev.Models.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class yemekler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public yemekler()
        {
            this.rezervasyon = new HashSet<rezervasyon>();
        }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public int menu_id { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string menu_adi { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public string menu_icerik { get; set; }
        [Required(ErrorMessage = "bu alan bos geçilemez")]
        public Nullable<int> menu_fiyat { get; set; }
       
        public string menu_fotograf { get; set; }
       

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<rezervasyon> rezervasyon { get; set; }
    }
}
